### ISSUE TITLE
cannot enter a negative starting balance for an account

### ISSUE THREAD

**Issue by randyjhunt** [jamis/bucketwise#10]
An attempt to enter a negative starting balance for an account results in a $0.00 value being assigned to the account. This is necessary to begin working with credit cards that have an existing balance.

**Comment by jamis** [comment]
Weird, this definitely used to work, because I'm tracking my credit card with bucketwise. I think this probably broke when I added the validations to events in 698ee80aa9da02b54e25bca7aa65e001dfe51a23 (the problem being that the starting balance is added as a deposit, and if the balance is negative, that gives you a deposit with a negative amount, which isn't legal).

I think the solution is to have the starting balance either as it's own beast (e.g. a new "starting_balance" line item role) or to use either 'deposit' or 'payment_source'  depending on whether the amount is positive or negative, respectively. I'll look into it more when I can.

**Comment by jamis** [comment]
This is now fixed in 2c109aca326a51f2e4417d0c21a7c4f72c42e1c8. I just went the easy way and used 'deposit' for positive starting balances, and 'payment_source' for negative ones. Eventually it might be nice to have a separate "starting_balance" line item role for reporting purposes, but whatever. :)
