### ISSUE TITLE
Make BucketWise heading at the top of the page link to the dashboard

### ISSUE THREAD

**Issue by KieranP** [jamis/bucketwise#12]
As the title says. It's a lot easier to click the heading than it it to click the dashboard link on some pages.

**Comment by jamis** [comment]
Good point. If a patch doesn't get submitted first, I'll look at adding this sometime next week.

**Comment by KieranP** [comment]
Made a patch at http://github.com/KieranP/bucketwise/commit/92b2903ac00fcf65bab748e0cea5f4406374b5b9 . Makes the BucketWise link to root path, which at the moment points to subscription index.

While I was at, I made changes for a few other little things I noticed while using BucketWise.

http://github.com/KieranP/bucketwise/commit/093a102b33f5f394644d355637f28fda1044698d

http://github.com/KieranP/bucketwise/commit/eb4c451b9a2fc706ac8548b4335a0d511b6ebb5f

http://github.com/KieranP/bucketwise/commit/8a873a572f4f3112491d2f54ef96214716c75dbb

**Comment by jamis** [comment]
Thanks! I've merged that in, as well as the fix for the button text. I don't want to change "expense" to "withdrawal", though -- when I grab lunch somewhere I don't think of that as a "withdrawal" (although it is, I know). I think "expense" describes it more accurately. Also, I'm on the fence about the database.yml change; I understand why you would want to ignore it, but at the same time, it's being tracked by git, and adding it to .gitignore muddies that distinction a bit.

**Comment by KieranP** [comment]
Re: expense/withdrawl - in most cases, but particularly in the context of a credit card expense edit, the text is confusing. "how much was paid" implies you paid some money to your credit card, rather than withdrew money from it. The "expense" text in the header remains the same. That change only affects the label in the form when you add/edit an expense.

**Comment by jamis** [comment]
Hmm. "Withdrawal" sounds more like I'm getting money out to put into my wallet, not to pay for something. "How much was paid", I think, is the right terminology for me; even for a credit card expense, it says (to me) "how much was paid (via credit card)", not "how much was paid (to the credit card)". I understand there may be cultural differences here, though, so I acknowledge that the text may mean otherwise to you. However, I'm probably going to leave that label as is for now.
