### ISSUE TITLE
Feature: Credit Card Limit

### ISSUE THREAD

**Issue by KieranP** [jamis/bucketwise#16]
It would be nice to be able to enter your credit card limit, and have the amount showing on the dashboard be red if you have 15% remaining, orange if you have between 15% and 80% remaining, and if you have over 80% remaining, it would be green. Gives a nice indication of how much left on your card (cause credit cards are always going to be red otherwise :-P ). It should be fairly easy to do I think (edit the account model, add a field, and use a helper to get the color for the credit card amount.

**Comment by jamis** [comment]
Neat idea! I don't have any immediate plans to implement this, but I wouldn't mind seeing it done, if anyone has a hankering to submit a patch.

**Comment by KieranP** [comment]
Found some time to do this today. Changes at

http://github.com/KieranP/bucketwise/commit/a440728ec86c4e8673c21d6c694f29d841632b3a

Current tests are all passing. Because there was very little changes to the model, and no changes in the controller, I didn't think tests would be needed in this case (mostly css, javascript, and view changes), but please feel free to point out if you know how something can be tested.

Had fun doing this. First time using Haml. Very strict template language. I like it!

**Comment by jamis** [comment]
Great job with this, thanks! A few minor issues I'd like to raise, but if you can take care of those I'd be happy to merge this in.

First, when I ran the mgiration and loaded up the dashboard, I got an error: "The error occurred while evaluating nil.abs". It came from line 18 of subscriptions_helper.rb. By manually adding a limit to my credit card account I got it to work, but it looks like the styles on the account balances on the dashboard have changed -- they're now gray, instead of black. (Also, the bucket balances are gray, which makes them really light when combined with the partial opacity that they were styled with before).

Could you please take a look at those issues? I think your change is very well implemented, otherwise, and I look forward to merging this in.

**Comment by KieranP** [comment]
If you pull in the original commit, then cherry pick this one, it should fix the issues you mentioned.

http://github.com/KieranP/bucketwise/commit/2762bead1bb9369d1c4a5601acf9ae6a6edbf335

**Comment by jamis** [comment]
Awesome. Sorry to take so long getting back to you, but my wife and I welcomed a new baby to our family last week, so things have been crazy (both before and after).

I've merged your changes in. Thanks for this! In using this a bit myself, I'm starting to think, though, that simply changing the text color is perhaps not informative enough regarding the how much of one's available credit one has consumed. I think it might be better to show the actual percentage consumed, along with how much credit is available.

I've added an item to the TODO file, to this effect. I think what you've done is fine for now, though, so feel free to let someone else come along and do the rest of the work if you want. :)
